# Generated by Django 3.0.4 on 2020-03-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_period', models.DateTimeField(verbose_name='Report_Period')),
                ('terminal', models.CharField(max_length=100, verbose_name='Terminal')),
                ('arrival_departure', models.CharField(choices=[('Arrival', 'Arrival'), ('Departure', 'Departure')], max_length=50, verbose_name='Arrival_Departure')),
                ('domestic_international', models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=50, verbose_name='Domestic_International')),
                ('passenger_count', models.IntegerField(blank=True, null=True, verbose_name='Passenger_Count')),
            ],
        ),
    ]
