# Generated by Django 3.0.4 on 2020-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirportTraffic', '0002_auto_20200314_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='arrival_departure',
            field=models.CharField(choices=[('Arrival', 'Arrival'), ('Departure', 'Departure')], max_length=50, verbose_name='arrival_departure'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='domestic_international',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('International', 'International')], max_length=50, verbose_name='domestic_international'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='passenger_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='passenger_count'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='report_period',
            field=models.DateTimeField(verbose_name='report_period'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='terminal',
            field=models.CharField(max_length=100, verbose_name='terminal'),
        ),
    ]
