# Generated by Django 3.0.4 on 2020-03-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AirportTraffic', '0004_auto_20200314_0843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airport',
            new_name='AirportModel',
        ),
    ]
